### ISSUE TITLE
Don't use unescaped SVG data URIs

### ISSUE THREAD

**Issue by d-eisenga** [wearereasonablepeople/webpacker#27]
Deprecation warning in Chrome:
> Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

Currently some SVGs are being imported as `data:image/svg+xml;charset=utf-8` data URIs which include `#` for colors or for referring to filters via id.

**Comment by d-eisenga** [comment]
@renanborgez I was also unable to reproduce the problem in a new project, so it seems the underlying library has since addressed the issue. I think this issue can be closed.

**Comment by renanborgez** [comment]
@d-eisenga 👍
