### ISSUE TITLE
ESlint is not working

### ISSUE THREAD

**Issue by renanborgez** [wearereasonablepeople/webpacker#34]
![image](https://user-images.githubusercontent.com/1863024/43444597-77e180da-94a4-11e8-8556-50bfc13cfd23.png)

There is a `.eslintrc.json` file but there is no eslint modules installed on package.json

Using: macOS High Sierra 10.13.6
node version: `v8.11.3` |` v10.5.0`
npm version: `v5.6.3` | `v6.1.0`
eslint version: `v4.19.1`

command used: `eslint .`

**Comment by dicearr** [comment]
It is a missing dependency. `eslint-config-warp` needs to be added to `devDependencies`.

**Comment by renanborgez** [comment]
#38
