### ISSUE TITLE
Postcss is deprecated

### ISSUE THREAD

**Issue by renanborgez** [wearereasonablepeople/webpacker#35]
![image](https://user-images.githubusercontent.com/1863024/43445512-dcac1f00-94a6-11e8-9719-193bcb784cba.png)

![image](https://user-images.githubusercontent.com/1863024/43445538-edb74dc4-94a6-11e8-9e45-7a141188a40d.png)

The postcss-next is deprecated and they recommend to switch to https://preset-env.cssdb.org/

**Comment by dicearr** [comment]
@indebanvdhamer, @renanborgez Can I tackle this?

**Comment by renanborgez** [comment]
@dicearr 👍
