### ISSUE TITLE
Samples are installing webpacker from Github master branch

### ISSUE THREAD

**Issue by dicearr** [wearereasonablepeople/webpacker#45]
This is how samples are installing `webpacker`:

https://github.com/wearereasonablepeople/webpacker/blob/494e746385985abec6747ca453d79e36d88d9ca5/samples/react-and-sass/package.json#L13-L16

I would prefer to remove the dependency and import `webpacker` from the fs itself. That would make the process of developing slightly better because it would be possible to test the new features in the samples.

In `react-and-sass` it should be enough with replacing the scripts:

https://github.com/wearereasonablepeople/webpacker/blob/494e746385985abec6747ca453d79e36d88d9ca5/samples/react-and-sass/package.json#L7

with:

```json
{
  "start": "node ../../webpacker build"
}
```

And the following import:

https://github.com/wearereasonablepeople/webpacker/blob/494e746385985abec6747ca453d79e36d88d9ca5/samples/react-and-sass/.webpacker.js#L2

with:

```js
const {setLoader, setPlugin} = require('../../utils');
```

**Comment by renanborgez** [comment]
@dicearr 👍
